### PR TITLE
Use the RTC in MIX mode and convert timeout values

### LINKED ISSUE #9: LoRaWAN with low power and RTC
Hi, 
I was trying to use your example of sending data via lorawan and the library "STM32LowPower.h" and I get an error that two functions have multiple definitions. 

```
.: ../../../..\libraries\STM32duino_RTC\rtc.c.o: in function `HAL_RTC_AlarmAEventCallback':
rtc.c:(.text.HAL_RTC_AlarmAEventCallback+0x0): multiple definition of `HAL_RTC_AlarmAEventCallback'; ..\..\..\.\libraries\STM32duino_RTC\rtc.c.o: in function `RTC_Alarm_IRQHandler':
rtc.c:(.text.RTC_Alarm_IRQHandler+0x0): multiple definition of `RTC_Alarm_IRQHandler'; 
..\..\..\.\libraries\STM32LoRaWAN-main\BSP\rtc.c.o:rtc.c:(.text.RTC_Alarm_IRQHandler+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
```
Is crashing with another library that has the low power that is "STM32RTC.h" it is because they have the same functions.
How can I fix this crash?

### PR DESCRIPTION
**Pull request by FRASTM**
When the RTC is using subsecond as a nb of milliseconds (cf PR https://github.com/stm32duino/STM32RTC/pull/95)

The LoraWan is always  using timeout values as a nb of ticks
Ticks is the RTC count unit when running in BINATY or MIX mode to be 1000ms/fqce_apre = 1000 / 256 ~ 3.9ms when the RTC is clocked by the LSE (32768Hz) 
fqce_apre = LSE clock/ (Async prediv + 1) 

Setting the Lorawan alarm (ALARM B) to expire in a nb of ticks, requires a conversion to when the RTC_StartAlarm() has a subsecond parameter expressed in milliseconds : 
Timeout in milliseconds = timeout in ticks * 1000 / 256 ( + 1 to compensate division uncertainty)

Requires RTC https://github.com/stm32duino/STM32RTC/pull/95

Fixes #9

### CODE REVIEW

**Comment by FRASTM** [comment]
Adding another commit with a new sketch to send the current calendar on LoRa

**Comment by FRASTM** [comment]
Calculate the ck_apre from the RTC clock source and the Async prescaler (prediv_A )
 ck_apre = RTC_clock / (prediv_A +1) given by the ref Manual.
This is 256 when LSE clock and prediv_A = 0x7F  (default)

**Comment by fpistm** [comment]
Dependency: https://github.com/stm32duino/STM32RTC/releases/tag/1.4.0

**Review by fpistm — APPROVED** [review]
LGTM

**Pull request merged**
