### PR TITLE
STM32CubeWL: Update to 1.3.0

### PR DESCRIPTION
**Pull request by matthijskooijman**
This updates the cube code to the recently released 1.3.0 version, and makes some other small changes. Basic OTAA and ABP operation has been tested, but not a full test yet.

This was tested with the current master version of https://github.com/stm32duino/Arduino_Core_STM32.

### CODE REVIEW

**Review by fpistm — APPROVED** [review]
LGTM
Thanks @matthijskooijman

**Comment by fpistm** [comment]
@matthijskooijman 
you can merge it if it is fine on your side.

**Comment by matthijskooijman** [comment]
I did more thorough testing now, rerunning the test plan I wrote for the first release (Maybe we should publish that somewhere at some point). All tests passed as before, I did see one change in behavior in decreasing of the datarate for the ADR code (but that's probably a bugfix, 1.2.0 would decrease the datarate twice in a row at some point, while 1.3.0 uses consistent 32-packet spacing).

With that, this is ready to merge. I wanted to merge through github, but then accidentally pushed to main directly (and I cannot seem to re-open this pullrequest even after quickly force-pushing main), so I'll just leave it like this :-)

I also think this is a good moment to tag a release and submit to the Arduino library manager. @fpistm do you have a suggestion for a version number? Should we go ahead and use 1.0.0 right away, or stick to 0.1.0 or so for a while until we get some feedback from users?

**Comment by fpistm** [comment]
Hi @matthijskooijman 
Thanks. No worry. I will tag and release. Probably 0.1.0 is better.

**Pull request merged**
